// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joxqhkwwokfygnygmbto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveHFoa3d3b2tmeWdueWdtYnRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDkwMTEsImV4cCI6MjA2ODA4NTAxMX0.RDPRcAMRNsH0qfCm7DVC7pWmKRw9Pork5hyqsDDlRP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});